use camino::Utf8PathBuf;
use std::process::Command;

pub fn format(path: &Utf8PathBuf) -> Result<(), anyhow::Error> {
    let csharpier = Command::new("csharpier")
        .arg("format")
        .arg("--include-generated")
        .arg(path)
        .spawn()?;

    let output = csharpier.wait_with_output()?;
    if !output.status.success() {
        Err(std::io::Error::other(
            format!(
                "command returned non-zero exit status: {:?}",
                output.status.code()
            ),
        ))?;
    }
    Ok(())
}

pub fn add_header(bindings: String) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let header = format!(
        r##"// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v{version}
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable

"##
    );

    header + &bindings
}
